version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crca"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3xjp37u3nycd"
s3_prefix = "crca"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
